// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepTracker.UgniusFalze.Models;

#nullable disable

namespace SleepTracker.UgniusFalze.Migrations
{
    [DbContext(typeof(SleepRecordContext))]
    partial class SleepRecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SleepTracker.UgniusFalze.Models.SleepRecord", b =>
                {
                    b.Property<int>("SleepRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RecordEnd")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<int>("RecordStart")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.HasKey("SleepRecordId");

                    b.ToTable("SleepRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
